image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
    - name: Copy environment file 
      init: cp -n ${GITPOD_REPO_ROOT}/sample.env ${GITPOD_REPO_ROOT}/.env
    - name: Install dependencies
      command: pip3 install -r requirements.txt 
