image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
    - name: Install dependencies
      init: pip3 install -r requirements.txt
      command: python3 app.py
      openMode: tab-after
